/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright (C) 2024 Jon Evans <jon@craftyjon.com>
 * Copyright (C) 2024 KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package kiapi.board.commands;

import "common/types/base_types.proto";
import "common/types/embedded_files.proto";
import "google/protobuf/any.proto";
import "common/types/enums.proto";
import "common/types/project_settings.proto";
import "board/board.proto";
import "board/board_rules.proto";
import "board/board_types.proto";
import "board/board_jobs.proto";
import "common/types/jobs.proto";
import "common/commands/editor_commands.proto";

/*
 * Board stackup and properties
 */

message GetBoardStackup
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

message BoardStackupResponse
{
  kiapi.board.BoardStackup stackup = 1;
}

// Changes the stackup for the given board according to the contents of the message (**not yet implemented**)
// WARNING: any existing content on layers that are removed by this call is deleted.  This operation cannot be undone.
// Returns BoardStackupResponse with the updated stackup, in normalized form
message UpdateBoardStackup
{
  kiapi.common.types.DocumentSpecifier board = 1;
  kiapi.board.BoardStackup stackup = 2;
}

message GetBoardEnabledLayers
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

message BoardEnabledLayersResponse
{
  // The number of copper layers enabled in this board.
  uint32 copper_layer_count = 1;

  // A list of all layers enabled in this board, including copper layers and ones which cannot be disabled.
  repeated kiapi.board.types.BoardLayer layers = 2;
}

// Changes which layers are enabled in the board stackup
// WARNING: any existing content on layers that are removed by this call is deleted.  This operation cannot be undone.
// Returns BoardEnabledLayersResponse with the updated layer set.
message SetBoardEnabledLayers
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // The number of copper layers to enable in the board.  Currently, this must be an even number >= 2.
  uint32 copper_layer_count = 2;

  // The non-copper layers to enable.  Note that any copper layers in this list are ignored; copper layers are enabled
  // by setting copper_layer_count.  Note that the F/B.Courtyard, Edge.Cuts, and Margin layers cannot be disabled and
  // will be present in the board even if they are omitted from this list.
  repeated kiapi.board.types.BoardLayer layers = 3;
}

// Returns kiapi.common.types.EmbeddedFiles
message GetEmbeddedFiles
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

// Appends embedded files to the board.  Returns Empty.
message AddEmbeddedFiles
{
  kiapi.common.types.DocumentSpecifier board = 1;
  kiapi.common.types.EmbeddedFiles files = 2;
}

// Replaces all embedded files in the board.  Returns Empty.
message SetEmbeddedFiles
{
  kiapi.common.types.DocumentSpecifier board = 1;
  kiapi.common.types.EmbeddedFiles files = 2;
}

message GetGraphicsDefaults
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

message GraphicsDefaultsResponse
{
  kiapi.board.GraphicsDefaults defaults = 1;
}

enum CustomRulesStatus
{
  CRS_UNKNOWN = 0;
  CRS_NONE = 1;
  CRS_VALID = 2;
  CRS_INVALID = 3;
}

message GetBoardDesignRules
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

message SetBoardDesignRules
{
  kiapi.common.types.DocumentSpecifier board = 1;
  kiapi.board.BoardDesignRules rules = 2;
}

message BoardDesignRulesResponse
{
  kiapi.board.BoardDesignRules rules = 1;
  CustomRulesStatus custom_rules_status = 2;
}

message GetCustomDesignRules
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

// Returns CustomRulesResponse
message SetCustomDesignRules
{
  kiapi.common.types.DocumentSpecifier board = 1;
  repeated kiapi.board.CustomRule rules = 2;
}

message CustomRulesResponse
{
  CustomRulesStatus status = 1;
  repeated kiapi.board.CustomRule rules = 2;
  string error_text = 3;
}

enum BoardOriginType
{
  BOT_UNKNOWN = 0;
  BOT_GRID = 1;
  BOT_DRILL = 2;
}

// Returns a Vector2 with the specified origin point
message GetBoardOrigin
{
  kiapi.common.types.DocumentSpecifier board = 1;

  BoardOriginType type = 2;
}

message SetBoardOrigin
{
  kiapi.common.types.DocumentSpecifier board = 1;

  BoardOriginType type = 2;

  kiapi.common.types.Vector2 origin = 3;
}

message GetBoardLayerName
{
  kiapi.common.types.DocumentSpecifier board = 1;

  kiapi.board.types.BoardLayer layer = 2;
}

message BoardLayerNameResponse
{
  // The name of the layer shown in the KiCad GUI, which may be a default value like "F.Cu" or may
  // have been customized by the user.
  string name = 1;
}

// Since: 10.0.6
// Returns BoardLayerResponse
message GetBoardLayerByName
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // A name to retrieve the layer ID for, which may be a user-customized or a KiCad standard one.
  string name = 2;
}

/*
 * Net management
 */

message GetNets
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // If provided, will only return nets that belong to the given netclass.
  // If more than one netclass_filter is given, nets belonging to any of the given classes will
  // be returned.
  repeated string netclass_filter = 2;
}

message NetsResponse
{
  repeated kiapi.board.types.Net nets = 1;
}

// Retrieve all the copper items belonging to a certain net or set of nets
// returns kiapi.common.commands.GetItemsResponse
message GetItemsByNet
{
  // Specifies which document to query, which fields to return, etc.
  kiapi.common.types.ItemHeader header = 1;

  // Optional list of item types to filter by.  If not provided, will return pads, vias,
  // tracks, and zones.
  repeated kiapi.common.types.KiCadObjectType types = 2;

  // Removed; NetCode was deprecated before a handler for this was written
  // repeated kiapi.board.types.NetCode net_codes = 3;

  // A list of nets to filter items by
  repeated kiapi.board.types.Net nets = 4;
}

// Retrieve all the copper items belonging to a certain net class or set of net classes
// returns kiapi.common.commands.GetItemsResponse
message GetItemsByNetClass
{
  // Specifies which document to query, which fields to return, etc.
  kiapi.common.types.ItemHeader header = 1;

  // Optional list of item types to filter by.  If not provided, will return pads, vias,
  // tracks, and zones.
  repeated kiapi.common.types.KiCadObjectType types = 2;

  // A list of net class names to filter items by
  repeated string net_classes = 3;
}

// Retrieve all copper-connected items connected to one or more source items
// returns kiapi.common.commands.GetItemsResponse
message GetConnectedItems
{
  // Specifies which document to query, which fields to return, etc.
  kiapi.common.types.ItemHeader header = 1;

  // One or more item IDs used as the source set for connectivity queries
  repeated kiapi.common.types.KIID items = 2;

  // Optional list of item types to return. If empty, all connected item types are returned.
  repeated kiapi.common.types.KiCadObjectType types = 3;
}

// A net may be part of multiple classes that have a priority ordering, which will result in a
// composite "effective" netclass containing the merged/overridden properties of all the constituent
// netclasses it contains.  This message retrieves this effective netclass for a net or list of
// nets.
// Returns NetClassForNetsResponse
message GetNetClassForNets
{
  repeated kiapi.board.types.Net net = 1;
}

message NetClassForNetsResponse
{
  // Map of net name to netclass info
  map<string, kiapi.common.project.NetClass> classes = 1;
}

/*
 * Netlist import
 */

// How schematic components are matched to board footprints during netlist import.
enum NetlistMatchMode
{
  NMM_UNKNOWN = 0;
  NMM_UUID = 1;      // Match by unique ID.
  NMM_REFERENCE = 2; // Match by reference designator.
}

// Imports a netlist file exported from the schematic and updates the board.
// Returns ImportNetlistResponse.
message ImportNetlist
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // Path to the netlist file.
  string netlist_path = 2;

  // If true, report planned changes without modifying the board.
  bool dry_run = 3;

  NetlistMatchMode match_mode = 4;

  bool delete_extra_footprints = 5;
  bool update_footprints = 6;
  bool transfer_groups = 7;
  bool override_locks = 8;

  // Copy symbol field values to the footprints (default true; set to false to keep the
  // footprints' fields).  Since 11.0
  optional bool update_fields = 9;

  // Remove footprint fields that the symbol does not have (only with update_fields).  Since 11.0
  bool remove_extra_fields = 10;
}

message ImportNetlistResponse
{
  uint32 error_count = 1;
  uint32 warning_count = 2;
  uint32 new_footprint_count = 3;

  // Human-readable report of changes and any warnings or errors.
  string report = 4;
}

/*
 * Blocking operations
 */

// Refills some or all zones on the board.
// When zones is empty and a board editor is running, all zones are refilled in the background:
// Empty is returned immediately and KiCad returns ApiStatusCode.AS_BUSY to all future API
// requests until the fill completes.  When specific zones are given, or in headless sessions,
// the fill runs synchronously and the response is not sent until it has completed.
message RefillZones
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // A list of zones to refill.  If empty, all zones are refilled.
  repeated kiapi.common.types.KIID zones = 2;
}

/*
 * Utilities
 */

// Computes the polygon representation of a pad, merging any custom shapes together.
// This representation will approximate curves as a series of segments.
message GetPadShapeAsPolygon
{
  // The board to process
  kiapi.common.types.DocumentSpecifier board = 1;

  // A list of one or more pads to process
  repeated kiapi.common.types.KIID pads = 2;

  // The layer to process
  kiapi.board.types.BoardLayer layer = 3;
}

// Returned from GetPadShapeAsPolygon.  The pads and polygons repeated fields will have the same length
// and can be treated as a list of tuples.
message PadShapeAsPolygonResponse
{
  // The pads that were processed
  repeated kiapi.common.types.KIID pads = 1;

  // The polygon representation of each pad
  repeated kiapi.common.types.PolygonWithHoles polygons = 2;
}

// Tests if the given set of items with padstacks (pads or vias) has content on the given set of layers.
// This is a dynamic call rather than a property of the padstack because pads and vias can be set to only include
// shapes on connected copper layers, and whether or not the pad is connected can't be determined in isolation.
// To optimize API call performance, multiple items and multiple layers to test may be passed in with this
// command message.  The return will include the results for each valid item on each valid layer.
// Note that not all layers make sense for a given item (for example, testing against BL_UNDEFINED never makes
// sense).  In general, the internal KiCad APIs will not return an error when testing non-sensical layers for a given
// item, and instead will return a default of "true" for any such layers.
message CheckPadstackPresenceOnLayers
{
  kiapi.common.types.DocumentSpecifier board = 1;

  repeated kiapi.common.types.KIID items = 2;

  repeated kiapi.board.types.BoardLayer layers = 3;
}

enum PadstackPresence
{
  PSP_UNKNOWN = 0;
  PSP_PRESENT = 1;      // The padstack has a shape on a given layer (is flashed)
  PSP_NOT_PRESENT = 2;  // The padstack has no shape on a given layer (is not flashed)
}

message PadstackPresenceEntry
{
  kiapi.common.types.KIID item = 1;
  kiapi.board.types.BoardLayer layer = 2;
  PadstackPresence presence = 3;
}

message PadstackPresenceResponse
{
  repeated PadstackPresenceEntry entries = 1;
}

// DRC markers

// Deprecated - use common.types.RuleSeverity
enum DrcSeverity // Since 10.0
{
  DRS_UNKNOWN = 0;
  DRS_WARNING = 1;
  DRS_ERROR = 2;
  DRS_EXCLUSION = 3;
  DRS_IGNORE = 4;
  DRS_INFO = 5;
  DRS_ACTION = 6;
  DRS_DEBUG = 7;
  DRS_UNDEFINED = 8;
}

// Returns InjectDrcErrorResponse
message InjectDrcError
{
  kiapi.common.types.DocumentSpecifier board = 1;

  DrcSeverity severity = 2;

  string message = 3;

  kiapi.common.types.Vector2 position = 4;

  repeated kiapi.common.types.KIID items = 5;
}

message InjectDrcErrorResponse
{
  kiapi.common.types.KIID marker = 1;
}

// PCB editor commands

// returns BoardLayers
message GetVisibleLayers
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

message BoardLayerResponse
{
  kiapi.board.types.BoardLayer layer = 1;
}

message BoardLayers
{
  repeated kiapi.board.types.BoardLayer layers = 1;
}

message SetVisibleLayers
{
  kiapi.common.types.DocumentSpecifier board = 1;

  repeated kiapi.board.types.BoardLayer layers = 2;
}

// returns BoardLayerResponse
message GetActiveLayer
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

message SetActiveLayer
{
  kiapi.common.types.DocumentSpecifier board = 1;

  kiapi.board.types.BoardLayer layer = 2;
}

enum InactiveLayerDisplayMode
{
  ILDM_UNKNOWN = 0;
  // Inactive layers are shown
  ILDM_NORMAL = 1;
  // Inactive layers are shown with dimmed colors
  ILDM_DIMMED = 2;
  // Inactive layers are hidden
  ILDM_HIDDEN = 3;
}

enum NetColorDisplayMode
{
  NCDM_UNKNOWN = 0;
  // Net and netclass colors are shown in the ratsnest and on all copper items
  NCDM_ALL = 1;
  // Net and netclass colors are shown in the ratsnest only
  NCDM_RATSNEST = 2;
  // Net and netclass colors are not shown
  NCDM_OFF = 3;
}

enum BoardFlipMode
{
  BFM_UNKNOWN = 0;
  // Normal ("non-flipped") mode
  BFM_NORMAL = 1;
  // "Flipped" mode, viewed from the back and mirrored around the X axis
  BFM_FLIPPED_X = 2;
}

enum RatsnestDisplayMode
{
  RDM_UNKNOWN = 0;
  // Ratsnest lines are drawn to objects even if they are on hidden layers
  RDM_ALL_LAYERS = 1;
  // Ratsnest lines are hidden when at least one endpoint is an item on a hidden layer
  RDM_VISIBLE_LAYERS = 2;
}

message BoardEditorAppearanceSettings
{
  InactiveLayerDisplayMode inactive_layer_display = 1;

  NetColorDisplayMode net_color_display = 2;

  BoardFlipMode board_flip = 3;

  RatsnestDisplayMode ratsnest_display = 4;
}

// Returns BoardEditorAppearanceSettings
message GetBoardEditorAppearanceSettings
{
}

message SetBoardEditorAppearanceSettings
{
  BoardEditorAppearanceSettings settings = 1;
}

// Returns BoardPlotSettingsResponse
message GetBoardPlotSettings
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

message SetBoardPlotSettings
{
  kiapi.common.types.DocumentSpecifier board = 1;
  kiapi.board.jobs.BoardPlotSettings plot_settings = 2;
}

message BoardPlotSettingsResponse
{
  kiapi.board.jobs.BoardPlotSettings plot_settings = 1;
}

enum BoardFlipDirection
{
  BFD_UNKNOWN    = 0;
  BFD_LEFT_RIGHT = 1; // Flip left to right (around the Y axis)
  BFD_TOP_BOTTOM = 2; // Flip top to bottom (around the X axis)
}

// Flips one or more board items to the opposite side of the board.  Returns FlipItemsResponse.
message FlipItems
{
  kiapi.common.types.ItemHeader header = 1;

  repeated kiapi.common.types.KIID items = 2;

  // Direction to flip the items; BFD_TOP_BOTTOM if unspecified.
  BoardFlipDirection direction = 3;
}

message ItemFlipResult
{
  kiapi.common.commands.ItemStatus status = 1;

  // Updated version of the item after the flip (only populated when status.status is ISC_OK)
  google.protobuf.Any item = 2;
}

message FlipItemsResponse
{
  kiapi.common.types.ItemHeader header = 1;

  // Status of the overall request; may return IRS_OK even if no items were flipped
  kiapi.common.types.ItemRequestStatus status = 2;

  repeated ItemFlipResult flipped_items = 3;
}

// Requests placement of a footprint on a board
// Returns PlaceFromLibraryResponse
// Since: 11.0
message PlaceFootprintFromLibrary
{
  kiapi.common.types.ItemHeader header = 1;

  kiapi.common.types.LibraryIdentifier lib_id = 2;

  kiapi.common.types.Vector2 position = 3;

  // If unspecified, will use default orientation
  optional kiapi.common.types.Angle orientation = 4;

  // If unspecified, will place on F_Cu.  Footprint will be flipped if placed on B_Cu.
  optional kiapi.board.types.BoardLayer layer = 5;
}


//// Interactive commands ////
// These commands begin an interactive operation in the editor.
// They return a response immediately, but the editor will become busy
// and will not reply to further API commands until the user has finished
// the operation.
// These commands will return an error if received in a non-interactive context.

// Selects and begins an interactive move of the given item(s).
// NOTE: Takes ownership of the active commit, if one exists:
//       the move tool will push the commit when the user confirms the move,
//       or roll back the commit if the user cancels the move.  Keep this in
//       mind if using this command in combination with commands that create
//       or modify items using an explicit commit.
message InteractiveMoveItems
{
  kiapi.common.types.DocumentSpecifier board = 1;

  repeated kiapi.common.types.KIID items = 2;
}


//// DRC ////

// Runs the design rule checker on an open board, replacing the board's DRC markers with the
// results, exactly as the "kicad-cli pcb drc" job does.
// Returns DrcResultsResponse
// Since 11.0
message RunBoardJobDrc
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // Refill all zones before running the check
  bool refill_zones = 2;

  // Report every track clearance error instead of only the first per track
  bool report_all_track_errors = 3;

  // Compare the board against the schematic (schematic parity checks); requires either
  // schematic_netlist_path or a schematic next to the board file
  bool test_footprints_against_schematic = 4;

  // Optional path to a KiCad netlist file to use for the parity checks instead of netlisting the
  // project's schematic
  string schematic_netlist_path = 5;

  // Only RunJobSettings.async is honored: the check is queued on the same worker as the export
  // jobs and DrcResultsResponse comes back at once with `job` set to JS_RUNNING and a job id.
  // Progress is published as JobProgress events, GetJobStatus reports the outcome, and
  // GetDrcMarkers then reads the markers.  Until the check finishes the board and schematic
  // commands answer AS_BUSY, because the checker is rebuilding the document's markers.  The
  // document, output path and return_inline fields have no meaning for a check and are ignored;
  // an editor window runs the check synchronously regardless.
  // Since 11.0
  kiapi.common.types.RunJobSettings job_settings = 6;
}

// Since 11.0
message DrcResultsResponse
{
  // Every DRC, unconnected-item, and parity marker on the board, including excluded ones
  repeated kiapi.board.DrcMarker markers = 1;

  // Counts of markers by effective severity; excluded markers are only counted in exclusion_count
  uint32 error_count = 2;
  uint32 warning_count = 3;
  uint32 exclusion_count = 4;

  // Of the markers above, how many are unconnected-item (ratsnest) markers
  uint32 unconnected_count = 5;

  // Of the markers above, how many are schematic parity markers
  uint32 parity_count = 6;

  // Set only when the check was started asynchronously (RunJobSettings.async): status JS_RUNNING
  // and the job id to poll with GetJobStatus.  Every other field is then empty; read the markers
  // with GetDrcMarkers once the job reports JOB_STATE_FINISHED.
  // Since 11.0
  kiapi.common.types.RunJobResponse job = 7;
}

// Returns the DRC markers currently on the board without running the checker.
// Returns DrcResultsResponse
// Since 11.0
message GetDrcMarkers
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

// Marks the given markers as excluded (or clears the exclusion).  The board's exclusion list is
// updated so the change persists with the project.
// Since 11.0
message SetDrcMarkerExcluded
{
  kiapi.common.types.DocumentSpecifier board = 1;

  repeated kiapi.common.types.KIID markers = 2;

  bool excluded = 3;

  // Comment stored with the exclusion; ignored when clearing
  string comment = 4;
}

// Returns DrcSeveritiesResponse: the severity of every DRC rule type for the open board
// Since 11.0
message GetDrcSeverities
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

// Since 11.0
message DrcSeveritiesResponse
{
  repeated kiapi.board.DrcSeveritySetting severities = 1;
}

// Sets the severity of the given DRC rule types; rule types not listed keep their current
// severity.  Only error, warning, and ignore are accepted.
// Returns DrcSeveritiesResponse with the full resulting set
// Since 11.0
message SetDrcSeverities
{
  kiapi.common.types.DocumentSpecifier board = 1;

  repeated kiapi.board.DrcSeveritySetting severities = 2;
}


//// Ratsnest and net lengths ////

// One unrouted connection of the ratsnest, between two copper items
// Since 11.0
message RatsnestEdge
{
  // The net the connection belongs to; name and the board's current net code, as GetNets reports
  // them
  kiapi.board.types.Net net = 1;

  // The connected items (pad, via, track, zone) at each end
  kiapi.common.types.KIID source = 2;
  kiapi.common.types.Vector2 source_position = 3;
  kiapi.common.types.KIID target = 4;
  kiapi.common.types.Vector2 target_position = 5;

  // Straight-line distance between the ends
  kiapi.common.types.Distance length = 6;
}

// Returns the unrouted connections (the airlines) the connectivity engine computes, for the
// given nets or the whole board.  Returns RatsnestResponse
// Since 11.0
message GetRatsnest
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // Nets to report; empty reports every net
  repeated kiapi.board.types.Net nets = 2;
}

// Since 11.0
message RatsnestResponse
{
  repeated RatsnestEdge edges = 1;

  // Number of unrouted connections on the whole board (not only the requested nets)
  uint32 unrouted_count = 2;
}

// Returns UnroutedCountResponse
// Since 11.0
message GetUnroutedCount
{
  kiapi.common.types.DocumentSpecifier board = 1;
}

// Since 11.0
message UnroutedCountResponse
{
  uint32 unrouted_count = 1;

  // Nets with at least one unrouted connection
  uint32 unrouted_net_count = 2;
}

// Since 11.0
message NetLayerLength
{
  kiapi.board.types.BoardLayer layer = 1;
  kiapi.common.types.Distance length = 2;
}

// The net inspector's figures for one net
// Since 11.0
message NetLength
{
  kiapi.board.types.Net net = 1;

  uint32 pad_count = 2;
  uint32 via_count = 3;

  kiapi.common.types.Distance track_length = 4;
  kiapi.common.types.Distance via_length = 5;
  kiapi.common.types.Distance pad_to_die_length = 6;

  // track + via + pad-to-die
  kiapi.common.types.Distance total_length = 7;

  // Sum of the ratsnest airlines still to be routed
  kiapi.common.types.Distance unrouted_length = 8;

  repeated NetLayerLength layer_lengths = 9;

  // Propagation delay in picoseconds, when GetNetLengths.with_delays was set
  int64 total_delay_ps = 10;
}

// Returns NetLengthsResponse
// Since 11.0
message GetNetLengths
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // Nets to report; empty reports every net that has pads
  repeated kiapi.board.types.Net nets = 2;

  // Also compute propagation delays (slower)
  bool with_delays = 3;
}

// Since 11.0
message NetLengthsResponse
{
  repeated NetLength lengths = 1;
}


//// Footprint updates ////

// Replaces board footprints with their library version ("Update Footprints from Library"), or
// with another library footprint when new_footprint is set ("Change Footprints").  Each reset
// option defaults to true except reset_transform; send false to keep the board's version.
// Returns UpdateFootprintsFromLibraryResponse
// Since 11.0
message UpdateFootprintsFromLibrary
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // Footprints to update; empty updates every footprint on the board
  repeated kiapi.common.types.KIID footprints = 2;

  // Change the matched footprints to this library footprint instead of their own library id
  optional kiapi.common.types.LibraryIdentifier new_footprint = 3;

  // Only replace footprints that differ from the library (as the update dialog does)
  bool only_changed = 4;

  bool match_pad_positions = 5;
  optional bool delete_extra_texts = 6;
  optional bool reset_text_layers = 7;
  optional bool reset_text_effects = 8;
  optional bool reset_text_positions = 9;
  optional bool reset_text_content = 10;
  optional bool reset_fabrication_attributes = 11;
  optional bool reset_clearance_overrides = 12;
  optional bool reset_3d_models = 13;
  bool reset_transform = 14;
}

// Since 11.0
message UpdateFootprintsFromLibraryResponse
{
  uint32 updated_count = 1;

  // Footprints left alone because they matched the library (only_changed)
  uint32 unchanged_count = 2;

  // References of footprints whose library footprint could not be loaded
  repeated string missing = 3;

  repeated string messages = 4;
}


//// Teardrops ////

// Since 11.0
enum TeardropAction
{
  TDA_UNKNOWN = 0;

  // Enable teardrops with the board's default parameters for the target kind
  TDA_ADD = 1;

  // Disable teardrops
  TDA_REMOVE = 2;

  // Apply the parameters given in SetTeardrops.settings (mode included)
  TDA_SET = 3;
}

// Adds, removes or edits teardrops on pads, vias and track-to-track joints, as the global
// teardrop dialog does.  The teardrops themselves are regenerated by the commit.
// Returns SetTeardropsResponse
// Since 11.0
message SetTeardrops
{
  kiapi.common.types.DocumentSpecifier board = 1;

  TeardropAction action = 2;

  // Which items to affect; all false (and no items) means vias and every pad
  bool vias = 3;
  bool pth_pads = 4;
  bool smd_pads = 5;
  bool track_to_track = 6;

  // Restrict to these pads and vias instead of the kinds above
  repeated kiapi.common.types.KIID items = 7;

  // Restrict to items on these nets
  repeated kiapi.board.types.Net nets = 8;

  // Only pads and vias with round shapes
  bool round_shapes_only = 9;

  // Parameters for TDA_SET
  kiapi.board.types.PadTeardropSettings settings = 10;
}

// Since 11.0
message SetTeardropsResponse
{
  // Pads and vias whose teardrop settings the request actually changed.  Items that already had
  // the requested settings are not counted, so removing teardrops from a board that has none
  // reports zero.  Track-to-track teardrops are not counted here.
  uint32 item_count = 1;
}

// Removes every teardrop from the board and disables them on every pad and via.
// Returns SetTeardropsResponse
// Since 11.0
message RemoveTeardrops
{
  kiapi.common.types.DocumentSpecifier board = 1;
}


//// Autoplacement ////

// Since 11.0
enum AutoplaceResult
{
  APR_UNKNOWN = 0;
  APR_COMPLETED = 1;

  // The board has no outline to place within
  APR_NO_BOARD_OUTLINE = 2;
}

// Places footprints inside the board outline with the legacy autoplacer, as the Autoplace
// footprints tool does.  Returns AutoplaceFootprintsResponse
// Since 11.0
message AutoplaceFootprints
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // Footprints to place; empty places the footprints outside the board outline
  repeated kiapi.common.types.KIID footprints = 2;

  // Also place the footprints outside the board outline when footprints are listed
  bool include_offboard = 3;
}

// Since 11.0
message AutoplaceFootprintsResponse
{
  AutoplaceResult result = 1;

  uint32 placed_count = 2;
}


//// Global deletion ////

// Since 11.0
enum LockFilter
{
  LF_UNKNOWN = 0;
  LF_ALL = 1;
  LF_LOCKED = 2;
  LF_UNLOCKED = 3;
}

// Deletes every item of the given types, as the Global Deletions dialog does.  Zones on the
// Edge.Cuts layer and board outline shapes are only removed when board_edges is set.
// Returns GlobalDeletionResponse
// Since 11.0
message GlobalDeletion
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // Item types to delete: KOT_PCB_FOOTPRINT, KOT_PCB_TRACE, KOT_PCB_ARC, KOT_PCB_VIA, KOT_PCB_ZONE,
  // KOT_PCB_SHAPE, KOT_PCB_TEXT, KOT_PCB_TEXTBOX, KOT_PCB_DIMENSION, KOT_PCB_MARKER, KOT_PCB_GROUP
  repeated kiapi.common.types.KiCadObjectType types = 2;

  // Only items on these layers; empty means every layer
  repeated kiapi.board.types.BoardLayer layers = 3;

  // Defaults to LF_ALL
  LockFilter locked = 4;

  // Also delete board outline shapes (Edge.Cuts)
  bool board_edges = 5;

  // Also delete teardrop zones when KOT_PCB_ZONE is listed
  bool teardrops = 6;
}

// Since 11.0
message GlobalDeletionResponse
{
  uint32 deleted_count = 1;
}


//// Specctra session import ////

// Merges a Specctra session (.ses) file, the output of an external autorouter such as
// Freerouting, into an open board: the session's wires and vias become tracks, arcs and vias,
// and its placement moves the footprints it names, exactly as the board editor's
// File > Import > Specctra Session does.  The change is one undoable commit.
//
// The session is matched to the board by footprint reference, pad number and net name, and
// its via padstacks by the names the DSN export gave them, so it must have been routed from a
// DSN that RunBoardJobExportSpecctra produced from this same board (see that job); nets or
// layers the board no longer has are reported in the warnings and their items skipped.  Zone
// fills the router echoes back as polygon wires are ignored, and the board's DRC markers are
// cleared.  Returns ImportSpecctraSessionResponse
// Since 11.0
message ImportSpecctraSession
{
  kiapi.common.types.DocumentSpecifier board = 1;

  // Path of the session file.  Ignored when contents is set.
  string path = 2;

  // The session file's text, for a client that holds it in memory rather than on disk
  bytes contents = 3;

  // Delete the board's unlocked tracks, arcs and vias before adding the session's, as the
  // editor does (locked ones were exported as fixed wires and are not in the session).
  // Otherwise the session's items are added to whatever is on the board.
  bool replace_existing_tracks = 4;
}

// Since 11.0
message ImportSpecctraSessionResponse
{
  // Tracks and arcs created
  uint32 tracks_added = 1;

  uint32 vias_added = 2;

  // Tracks, arcs and vias deleted (only with replace_existing_tracks)
  uint32 tracks_removed = 3;

  // Footprints the session's placement moved, flipped or rotated
  uint32 footprints_moved = 4;

  // Problems that did not stop the import, such as items whose net, layer or padstack the
  // board does not have
  repeated string warnings = 5;
}


//// Graphics defaults ////

// Replaces the text and line defaults of the listed layer classes (Board Setup > Text &
// Graphics Defaults); the classes not listed are left alone.  Only the size, stroke width,
// italic and keep-upright attributes of the text are used.  Returns GraphicsDefaultsResponse
// Since 11.0
message SetGraphicsDefaults
{
  kiapi.common.types.DocumentSpecifier board = 1;

  kiapi.board.GraphicsDefaults defaults = 2;
}
