#!/usr/bin/env python3
"""Generate host/wasm/wasm_link_stubs.cpp -- the DATA half of the headless GUI stubs.

KICAD_HEADLESS_API does not build the GUI half of pcbnew and eeschema, but a number of the
sources it keeps still reference it from branches that only run with an editor frame.  On the
native host every one of those references is defined by host/headless_link_stubs.cpp (generated
by tools/gen_link_stubs.py, Mach-O spellings).

Under Emscripten, `-sERROR_ON_UNDEFINED_SYMBOLS=0` already covers the *functions*: wasm-ld
imports them and the JS glue installs a stub that throws, naming the symbol.  It does NOT cover
DATA -- an undefined vtable, typeinfo or class static is a hard wasm-ld error, because a wasm
data segment cannot be imported the same way.  That is what this file supplies: a zeroed
placeholder per undefined data symbol, named by its mangled spelling.

Nothing here is meant to be read at run time.  A crash reading one of these means a headless
guard is missing: fix the guard, or build the source the symbol comes from, then regenerate.

Usage (see tools/wasm/regen_wasm_link_stubs.sh, which finds the archives for you):
    tools/wasm/gen_wasm_link_stubs.py <output.cpp> <object or archive> ...
        [--defined-only <archive> ...]

`--defined-only` names libraries emcc adds to the link implicitly -- libc++, libc++abi,
compiler-rt, libc.  They are NOT on the ninja command line, so without them std::cout,
std::nothrow and every std::*::id would look undefined and get stubbed, which would replace the
real ones and break the runtime.  Their own undefined symbols are ignored.
"""
import subprocess
import sys
import os

LLVM_BIN = os.environ.get(
    "EM_LLVM_BIN", "/opt/homebrew/opt/emscripten/libexec/llvm/bin" )
NM = os.path.join( LLVM_BIN, "llvm-nm" )
CXXFILT = os.path.join( LLVM_BIN, "llvm-cxxfilt" )

# Plain (C linkage) data the link is missing.  The generator keys off C++ mangling, so it cannot
# find these on its own; they come from a probe link:
#
#     <the em++ line from `ninja -t commands host/kicad_api.js`> -Wl,--error-limit=0
#
# whose "undefined symbol: X" lines are, by construction, exactly the data wasm-ld cannot import.
# Anything on that list which deserves a REAL value goes in host/wasm/wasm_missing_globals.cpp
# instead; what is left is here.
EXTRA_DATA = [
    # const wxBitmap wxNullBitmap -- wxCore's null bitmap.  It cannot be defined for real: a
    # wxBitmap constructor is one of the imported-and-throwing function stubs, so an actual
    # definition would throw during static initialization, before main().  Nothing headless
    # reads it; BITMAP_BASE's device-side copy was removed on the native side already.
    ( "wxNullBitmap", "wxNullBitmap" ),
]

HEADER = '''/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright The KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * GENERATED by tools/wasm/gen_wasm_link_stubs.py -- do not edit by hand.
 *
 * The DATA half of the headless GUI stubs, for the Emscripten build only.  The function half is
 * handled by -sERROR_ON_UNDEFINED_SYMBOLS=0, which makes wasm-ld import each missing function
 * and gives it a JS stub that throws with the symbol's name.  wasm-ld cannot do that for data,
 * so every vtable, typeinfo, typeinfo name and class static that the kept sources still
 * reference is defined here as zeroed bytes.
 *
 * Nothing here is meant to be read.  If KiCad ever does read one of these the process will
 * misbehave rather than abort loudly -- that is the price of a data placeholder, and it is the
 * same trade host/headless_link_stubs.cpp makes on the native side.  host/STATUS-wasm-build.md
 * tracks what is left.
 *
 * Regenerate after ANY change that adds or removes a definition:
 *     tools/wasm/regen_wasm_link_stubs.sh build/wasm
 * A stale stub silently shadows a real definition.
 */

#include <cstddef>

namespace
{
/// One zeroed slot per stubbed data symbol.  Wide enough for the largest vtable KiCad names
/// (a wxWindow-derived dialog runs to a few hundred entries) so that a stray read stays inside
/// our own memory instead of walking into the next object.
struct KI_HEADLESS_DATA_STUB
{
    void* slots[512];
};
} // namespace

#define KI_HEADLESS_DATA( index, mangled, readable )                                     \\
    extern "C" KI_HEADLESS_DATA_STUB ki_headless_data_##index __asm__( mangled );        \\
    extern "C" KI_HEADLESS_DATA_STUB ki_headless_data_##index = {}

'''


def main() -> int:
    if len( sys.argv ) < 3:
        sys.stderr.write( __doc__ )
        return 2

    out_path = sys.argv[1]
    args = sys.argv[2:]

    if "--defined-only" in args:
        split = args.index( "--defined-only" )
        inputs, defined_only = args[:split], args[split + 1:]
    else:
        inputs, defined_only = args, []

    defined = set()
    undefined = set()

    # llvm-nm over every archive and object on the link line at once: anything still undefined
    # after the union of the defined sets is what wasm-ld will complain about.
    for i in range( 0, len( inputs ), 40 ):
        chunk = inputs[i:i + 40]
        out = subprocess.run( [NM, "--no-sort", "--extern-only"] + chunk,
                              capture_output=True, text=True ).stdout

        for line in out.splitlines():
            parts = line.split()

            if len( parts ) < 2:
                continue

            kind, name = parts[-2], parts[-1]

            if len( kind ) != 1:
                continue

            if kind in ( "U", "w" ):
                if kind == "U":
                    undefined.add( name )
            else:
                defined.add( name )

    # The implicit half of the link line: only its definitions count.
    for i in range( 0, len( defined_only ), 40 ):
        chunk = defined_only[i:i + 40]
        out = subprocess.run( [NM, "--no-sort", "--extern-only", "--defined-only"] + chunk,
                              capture_output=True, text=True ).stdout

        for line in out.splitlines():
            parts = line.split()

            if len( parts ) >= 2 and len( parts[-2] ) == 1:
                defined.add( parts[-1] )

    missing = sorted( n for n in ( undefined - defined ) if n.startswith( "_Z" ) )

    if not missing:
        sys.stderr.write( "no undefined C++ symbols\n" )

    # A demangling with no parameter list is data (a vtable, a typeinfo, a typeinfo name, a
    # class static).  Anything with '(' is a function, and Emscripten's own undefined-symbol
    # stubs cover those.
    demangled = subprocess.run( [CXXFILT], input="\n".join( missing ), capture_output=True,
                                text=True ).stdout.splitlines()

    data = [( m, d ) for m, d in zip( missing, demangled ) if "(" not in d]
    data += [e for e in EXTRA_DATA if e[0] not in defined]

    with open( out_path, "w" ) as f:
        f.write( HEADER )

        for index, ( mangled, readable ) in enumerate( data ):
            f.write( 'KI_HEADLESS_DATA( %d, "%s", "%s" );\n' % ( index, mangled, readable ) )

        f.write( "\n// %d data stubs; %d function references are left to Emscripten.\n"
                 % ( len( data ), len( missing ) - len( data ) ) )

    sys.stderr.write( "%d undefined C++ symbols: %d data stubs written to %s, "
                      "%d functions left to -sERROR_ON_UNDEFINED_SYMBOLS=0\n"
                      % ( len( missing ), len( data ), out_path, len( missing ) - len( data ) ) )
    return 0


if __name__ == "__main__":
    sys.exit( main() )
