/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright The KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * GENERATED by tools/wasm/gen_wasm_link_stubs.py -- do not edit by hand.
 *
 * The DATA half of the headless GUI stubs, for the Emscripten build only.  The function half is
 * handled by -sERROR_ON_UNDEFINED_SYMBOLS=0, which makes wasm-ld import each missing function
 * and gives it a JS stub that throws with the symbol's name.  wasm-ld cannot do that for data,
 * so every vtable, typeinfo, typeinfo name and class static that the kept sources still
 * reference is defined here as zeroed bytes.
 *
 * Nothing here is meant to be read.  If KiCad ever does read one of these the process will
 * misbehave rather than abort loudly -- that is the price of a data placeholder, and it is the
 * same trade host/headless_link_stubs.cpp makes on the native side.  host/STATUS-wasm-build.md
 * tracks what is left.
 *
 * Regenerate after ANY change that adds or removes a definition:
 *     tools/wasm/regen_wasm_link_stubs.sh build/wasm
 * A stale stub silently shadows a real definition.
 */

#include <cstddef>

namespace
{
/// One zeroed slot per stubbed data symbol.  Wide enough for the largest vtable KiCad names
/// (a wxWindow-derived dialog runs to a few hundred entries) so that a stray read stays inside
/// our own memory instead of walking into the next object.
struct KI_HEADLESS_DATA_STUB
{
    void* slots[512];
};
} // namespace

#define KI_HEADLESS_DATA( index, mangled, readable )                                     \
    extern "C" KI_HEADLESS_DATA_STUB ki_headless_data_##index __asm__( mangled );        \
    extern "C" KI_HEADLESS_DATA_STUB ki_headless_data_##index = {}

KI_HEADLESS_DATA( 0, "_ZN11wxGDIObject12ms_classInfoE", "wxGDIObject::ms_classInfo" );
KI_HEADLESS_DATA( 1, "_ZN15wxUpdateUIEvent17sm_updateIntervalE", "wxUpdateUIEvent::sm_updateInterval" );
KI_HEADLESS_DATA( 2, "_ZN17SCH_NAVIGATE_TOOL10g_BackLinkE", "SCH_NAVIGATE_TOOL::g_BackLink" );
KI_HEADLESS_DATA( 3, "_ZTI11ACTION_MENU", "typeinfo for ACTION_MENU" );
KI_HEADLESS_DATA( 4, "_ZTI11wxGDIObject", "typeinfo for wxGDIObject" );
KI_HEADLESS_DATA( 5, "_ZTI12DRAWING_TOOL", "typeinfo for DRAWING_TOOL" );
KI_HEADLESS_DATA( 6, "_ZTI12KIWAY_PLAYER", "typeinfo for KIWAY_PLAYER" );
KI_HEADLESS_DATA( 7, "_ZTI14EDA_BASE_FRAME", "typeinfo for EDA_BASE_FRAME" );
KI_HEADLESS_DATA( 8, "_ZTI14EDA_DRAW_FRAME", "typeinfo for EDA_DRAW_FRAME" );
KI_HEADLESS_DATA( 9, "_ZTI14GENERATOR_TOOL", "typeinfo for GENERATOR_TOOL" );
KI_HEADLESS_DATA( 10, "_ZTI14PCB_BASE_FRAME", "typeinfo for PCB_BASE_FRAME" );
KI_HEADLESS_DATA( 11, "_ZTI14PCB_EDIT_FRAME", "typeinfo for PCB_EDIT_FRAME" );
KI_HEADLESS_DATA( 12, "_ZTI14SCH_BASE_FRAME", "typeinfo for SCH_BASE_FRAME" );
KI_HEADLESS_DATA( 13, "_ZTI14SCH_EDIT_FRAME", "typeinfo for SCH_EDIT_FRAME" );
KI_HEADLESS_DATA( 14, "_ZTI15wxDataViewModel", "typeinfo for wxDataViewModel" );
KI_HEADLESS_DATA( 15, "_ZTI15wxGridTableBase", "typeinfo for wxGridTableBase" );
KI_HEADLESS_DATA( 16, "_ZTI15wxTextValidator", "typeinfo for wxTextValidator" );
KI_HEADLESS_DATA( 17, "_ZTI17SCH_NAVIGATE_TOOL", "typeinfo for SCH_NAVIGATE_TOOL" );
KI_HEADLESS_DATA( 18, "_ZTI17SYMBOL_EDIT_FRAME", "typeinfo for SYMBOL_EDIT_FRAME" );
KI_HEADLESS_DATA( 19, "_ZTI18PCB_SELECTION_TOOL", "typeinfo for PCB_SELECTION_TOOL" );
KI_HEADLESS_DATA( 20, "_ZTI18SCH_SELECTION_TOOL", "typeinfo for SCH_SELECTION_TOOL" );
KI_HEADLESS_DATA( 21, "_ZTI22EDA_3D_VIEWER_SETTINGS", "typeinfo for EDA_3D_VIEWER_SETTINGS" );
KI_HEADLESS_DATA( 22, "_ZTI22SCH_LINE_WIRE_BUS_TOOL", "typeinfo for SCH_LINE_WIRE_BUS_TOOL" );
KI_HEADLESS_DATA( 23, "_ZTI22wxGenericMessageDialog", "typeinfo for wxGenericMessageDialog" );
KI_HEADLESS_DATA( 24, "_ZTI25wxFileDialogCustomizeHook", "typeinfo for wxFileDialogCustomizeHook" );
KI_HEADLESS_DATA( 25, "_ZTI8PAD_TOOL", "typeinfo for PAD_TOOL" );
KI_HEADLESS_DATA( 26, "_ZTI8wxDialog", "typeinfo for wxDialog" );
KI_HEADLESS_DATA( 27, "_ZTI8wxWindow", "typeinfo for wxWindow" );
KI_HEADLESS_DATA( 28, "_ZTV10wxMenuBase", "vtable for wxMenuBase" );
KI_HEADLESS_DATA( 29, "_ZTV12SNAP_MANAGER", "vtable for SNAP_MANAGER" );
KI_HEADLESS_DATA( 30, "_ZTV14wxCommandEvent", "vtable for wxCommandEvent" );
KI_HEADLESS_DATA( 31, "_ZTV15DIALOG_GENDRILL", "vtable for DIALOG_GENDRILL" );
KI_HEADLESS_DATA( 32, "_ZTV15wxDataViewEvent", "vtable for wxDataViewEvent" );
KI_HEADLESS_DATA( 33, "_ZTV15wxTextValidator", "vtable for wxTextValidator" );
KI_HEADLESS_DATA( 34, "_ZTV16wxDataViewColumn", "vtable for wxDataViewColumn" );
KI_HEADLESS_DATA( 35, "_ZTV16wxTextDataObject", "vtable for wxTextDataObject" );
KI_HEADLESS_DATA( 36, "_ZTV17DIALOG_KICAD_DIFF", "vtable for DIALOG_KICAD_DIFF" );
KI_HEADLESS_DATA( 37, "_ZTV18DIALOG_EXPORT_2581", "vtable for DIALOG_EXPORT_2581" );
KI_HEADLESS_DATA( 38, "_ZTV18DIALOG_EXPORT_STEP", "vtable for DIALOG_EXPORT_STEP" );
KI_HEADLESS_DATA( 39, "_ZTV18WX_PT_ENTRY_DIALOG", "vtable for WX_PT_ENTRY_DIALOG" );
KI_HEADLESS_DATA( 40, "_ZTV18wxDataViewIconText", "vtable for wxDataViewIconText" );
KI_HEADLESS_DATA( 41, "_ZTV19wxRichMessageDialog", "vtable for wxRichMessageDialog" );
KI_HEADLESS_DATA( 42, "_ZTV20wxDataViewColumnBase", "vtable for wxDataViewColumnBase" );
KI_HEADLESS_DATA( 43, "_ZTV20wxwxMenuItemListNode", "vtable for wxwxMenuItemListNode" );
KI_HEADLESS_DATA( 44, "_ZTV21DIALOG_EXPORT_NETLIST", "vtable for DIALOG_EXPORT_NETLIST" );
KI_HEADLESS_DATA( 45, "_ZTV21DIALOG_MICROVIA_STACK", "vtable for DIALOG_MICROVIA_STACK" );
KI_HEADLESS_DATA( 46, "_ZTV21DIALOG_PLOT_SCHEMATIC", "vtable for DIALOG_PLOT_SCHEMATIC" );
KI_HEADLESS_DATA( 47, "_ZTV21DIALOG_TRACK_VIA_SIZE", "vtable for DIALOG_TRACK_VIA_SIZE" );
KI_HEADLESS_DATA( 48, "_ZTV21VALIDATE_MIN_MAX_CTRL", "vtable for VALIDATE_MIN_MAX_CTRL" );
KI_HEADLESS_DATA( 49, "_ZTV22VALIDATE_CHECKBOX_LIST", "vtable for VALIDATE_CHECKBOX_LIST" );
KI_HEADLESS_DATA( 50, "_ZTV23DIALOG_KICAD_MERGE_3WAY", "vtable for DIALOG_KICAD_MERGE_3WAY" );
KI_HEADLESS_DATA( 51, "_ZTV25SCH_EDIT_TOOLBAR_SETTINGS", "vtable for SCH_EDIT_TOOLBAR_SETTINGS" );
KI_HEADLESS_DATA( 52, "_ZTV26DIALOG_EXCHANGE_FOOTPRINTS", "vtable for DIALOG_EXCHANGE_FOOTPRINTS" );
KI_HEADLESS_DATA( 53, "_ZTV28SYMBOL_EDIT_TOOLBAR_SETTINGS", "vtable for SYMBOL_EDIT_TOOLBAR_SETTINGS" );
KI_HEADLESS_DATA( 54, "_ZTV29DIALOG_GEN_FOOTPRINT_POSITION", "vtable for DIALOG_GEN_FOOTPRINT_POSITION" );
KI_HEADLESS_DATA( 55, "_ZTV31DIALOG_PNS_DIFF_PAIR_DIMENSIONS", "vtable for DIALOG_PNS_DIFF_PAIR_DIMENSIONS" );
KI_HEADLESS_DATA( 56, "_ZTV31VALIDATE_MIN_PREFERRED_MAX_CTRL", "vtable for VALIDATE_MIN_PREFERRED_MAX_CTRL" );
KI_HEADLESS_DATA( 57, "_ZTV32DIALOG_TUNING_PATTERN_PROPERTIES", "vtable for DIALOG_TUNING_PATTERN_PROPERTIES" );
KI_HEADLESS_DATA( 58, "_ZTV4wxDC", "vtable for wxDC" );
KI_HEADLESS_DATA( 59, "_ZTV5wxPen", "vtable for wxPen" );
KI_HEADLESS_DATA( 60, "_ZTV6wxMenu", "vtable for wxMenu" );
KI_HEADLESS_DATA( 61, "_ZTV7wxBrush", "vtable for wxBrush" );
KI_HEADLESS_DATA( 62, "_ZTV8wxBitmap", "vtable for wxBitmap" );
KI_HEADLESS_DATA( 63, "_ZTVN5KIGFX17CONSTRUCTION_GEOME", "vtable for KIGFX::CONSTRUCTION_GEOM" );
KI_HEADLESS_DATA( 64, "wxNullBitmap", "wxNullBitmap" );

// 65 data stubs; 767 function references are left to Emscripten.
