#!/usr/bin/env python3
"""Regenerate host/headless_link_stubs.cpp from a failed headless link.

KICAD_HEADLESS_API drops the GUI half of pcbnew and eeschema, but a number of the sources it
keeps still reference it from branches that only run with an editor frame.  Until every one of
those has a headless guard, the native host links against aborting stubs.

Usage:
    ninja -C build/headless kicad-api-host-native 2>&1 | sed -n '/Undefined symbols/,$p' > undef.txt
    find build/dev -name '*.cpp.o' -print0 | xargs -0 -n40 -P8 nm -gU > devsyms.txt
    tools/gen_link_stubs.py undef.txt devsyms.txt > host/headless_link_stubs.cpp

`devsyms.txt` comes from a normal (option-OFF) build: it is what says whether a missing symbol is
a function (alias it to the abort thunk) or data (emit a zeroed placeholder), and it supplies the
mangled spellings the demangled linker message does not.
"""
import collections
import re
import subprocess
import sys

# Symbols no KiCad build defines in one place, hand-mangled.
EXTRA = {
    'FOOTPRINT_WIZARD_MANAGER::ReloadWizards()': ('__ZN24FOOTPRINT_WIZARD_MANAGER13ReloadWizardsEv', 'T'),
    'GENERATOR_TOOL_PNS_PROXY::ClearRouterChanges()': ('__ZN24GENERATOR_TOOL_PNS_PROXY18ClearRouterChangesEv', 'T'),
}

HEADER = '''/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright The KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * GENERATED by tools/gen_link_stubs.py -- do not edit by hand.
 *
 * Bring-up scaffolding for the native headless host.  KICAD_HEADLESS_API does not build the GUI
 * half of pcbnew and eeschema, but a number of the translation units it does keep still
 * *reference* it from branches that only run with an editor frame (a job handler falling back to
 * its dialog, a tool asking the selection tool for a selection, ...).  This file defines every
 * one of those references: functions alias a thunk that prints a backtrace and aborts, and
 * vtables, typeinfos, event ids and class statics are zeroed placeholders.
 *
 * Nothing here is meant to run.  An abort inside the thunk means a headless guard is missing:
 * fix the guard, or build the source the symbol comes from, then regenerate.  A *duplicate
 * symbol* error means a stub is no longer needed -- also regenerate.  host/STATUS-native-gate.md
 * tracks what is left.  The wasm build gets the same behaviour from
 * -sERROR_ON_UNDEFINED_SYMBOLS=0 and needs no equivalent.
 */

#include <cstdio>
#include <cstdlib>

#if defined( __APPLE__ )

#include <execinfo.h>

static void kicad_headless_gui_stub( const char* aSymbol )
{
    std::fprintf( stderr,
                  "\\nkicad-api-host: %s was called in a headless build.\\n"
                  "The caller below is missing its KICAD_HEADLESS_API guard.\\n",
                  aSymbol );

    void* frames[32];
    int   count = backtrace( frames, 32 );
    backtrace_symbols_fd( frames, count, 2 );
    std::abort();
}

/// Name the stub by its mangled symbol, so that the definition *is* the missing function.
#define KI_HEADLESS_STUB( index, mangled, readable )                      \\
    extern "C" __attribute__( ( visibility( "default" ) ) ) void ki_headless_stub_##index()  \\
            __asm__( mangled );                                                            \\
    extern "C" void ki_headless_stub_##index() { kicad_headless_gui_stub( readable ); }

'''


def main():
    undef_path, devsyms_path = sys.argv[1], sys.argv[2]

    types = {}
    for line in open(devsyms_path):
        line = line.rstrip('\n')
        if line.endswith('.o:'):
            continue
        m = re.match(r'^[0-9a-f]* ([A-Za-z]) (.+)$', line)
        if m:
            types.setdefault(m.group(2), m.group(1))

    names = list(types)
    stripped = '\n'.join(n[1:] if n.startswith('_') else n for n in names)
    demangled = subprocess.run(['c++filt', '-n'], input=stripped, capture_output=True,
                               text=True).stdout.split('\n')

    by_demangled = collections.defaultdict(list)
    for mangled, dem in zip(names, demangled):
        by_demangled[dem].append(mangled)

    undef = set()
    for block in re.split(r'\n(?=  ")', open(undef_path).read()):
        first = block.split('\n')[0].strip()
        if first.startswith('"'):
            undef.add(first[1:].split('", referenced from')[0])

    functions, data, unknown = [], [], []

    for sym in sorted(undef):
        candidates = by_demangled.get(sym) or by_demangled.get(sym.lstrip('_'))

        if not candidates:
            if sym in EXTRA:
                mangled, kind = EXTRA[sym]
                functions.append((mangled, sym))
            else:
                unknown.append(sym)
            continue

        for mangled in candidates:
            (functions if types[mangled] in 'Tt' else data).append((mangled, sym))

    if unknown:
        for sym in unknown:
            print('# could not mangle: ' + sym, file=sys.stderr)
        sys.exit('%d symbols could not be mangled; add them to EXTRA' % len(unknown))

    out = [HEADER]

    for index, (mangled, sym) in enumerate( functions ):
        out.append( 'KI_HEADLESS_STUB( %d, "%s", "%s" )' % ( index, mangled, sym.replace( '"', '' ) ) )

    out.append('')
    out.append('__asm__(')
    out.append('    ".data\\n"')

    for mangled, sym in data:
        out.append('    // %s' % sym)
        out.append('    ".globl %s\\n"' % mangled)
        out.append('    ".p2align 3\\n"')
        out.append('    "%s: .space 64\\n"' % mangled)

    out.append(');')
    out.append('')
    out.append('#endif')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
